name: Print Test Input

on:
  workflow_dispatch:
    inputs:
      test_input:
        description: 'Enter a test value'
        required: true
        default: 'Hello, World!'

jobs:
  print_input:
    runs-on: ubuntu-latest

    steps:
      - name: Print Test Input
        run: "echo 'The test input is: ${{ github.event.inputs.test_input }}'"
      - name: Test aws
        run: "aws --version"
      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli
      - name: Test AWS SAM CLI Version
        run: sam --version
        
